### ISSUE TITLE
功能建议 Function suggestion

### ISSUE THREAD

**Issue by chainofhonor** [ZXfkSIE/ThousandPlayer#2]
1.增加播放顺序调整功能 比如随机播放 
2.随机播放的时候可以跨列表,即随机播放所有歌曲
3.添加按照最后修改时间排序

1. Add play sequence adjustment function, such as random play 
2. When playing randomly, you can cross the list, that is, play all songs randomly 
3. Add sort by last modified time

**Comment by ZXfkSIE** [comment]
1. 随机播放早就有了，在主窗口最右边的那个按钮
2. 暂时不考虑，影响的东西太多且非必要
3. 可以考虑添加

**Comment by ZXfkSIE** [comment]
e060a20939b364396906b5f1fbe3fa3e9a17fc2a
